name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Checkout du code
      uses: actions/checkout@v3

    - name: ✅ Test de base
      run: |
        echo "✅ Le workflow fonctionne !"
        echo "📌 Déclenché par : ${{ github.event_name }}"
